name: Deplooy Alert
on:
  push:
    branches-ignore:
      - "main"

permissions:
  id-token: write

env:
  ARMTEMPLATE_PATH: .arm
  RESOURCEGROUPNAME: ${{ github.actor }}-demo-rg

jobs:
  build:
    name: Provisioning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
      name: checkout
    - name: Login to Azure
      uses: azure/login@v1.4.6
      continue-on-error: false
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Azure CLI script
      uses: Azure/cli@v1.0.7
      with:
        azcliversion: 2.44.1
        inlineScript: |
            az deployment group create --name DemoAlert --resource-group quotto-demo-rg --template-file ./arm/template.json --parameters target_function_id="${{ secrets.TARGET_FUNCTION_ID }}" webhook_function_id="${{ secrets.WEBHOOK_FUNCTION_ID }}" webhook_function_trigger_url="${{ secrets.WEBHOOK_FUNCTION_TRIGGER_URL }}"
